### ISSUE TITLE
might want to make the reference to dbrecord a git location, rather than local

### ISSUE THREAD

**Issue by mwotton** [byteally/dbrecord-opaleye#2]
or at least mention a setup procedure.

**Comment by mwotton** [comment]
(in stack.yaml, i mean.)

**Comment by keyanmk2** [comment]
@mwotton Thanks for reporting! We have fixed the issue.

**Comment by mwotton** [comment]
(tangentially, this is very exciting work - if it had been around a few months ago i might have been able to keep using opaleye.)
