### ISSUE TITLE
Primary Keys are not handled properly during insertion

### ISSUE THREAD

**Issue by xldenis** [byteally/dbrecord-opaleye#6]
Auto incrementing primary keys are not handled properly. Insertion should not include the primary key in the SQL. There is also no way to specify this in the table format.

**Comment by mageshb** [comment]
For Auto incrementing column, you can configure `HasDefault` associated type in the Table class.
By doing so, that column will be become optional during write(Insert & Update).
Example:
https://github.com/byteally/dbrecord-opaleye/blob/master/test/Spec.hs#L97
https://github.com/byteally/dbrecord-opaleye/blob/master/test/Spec.hs#L206-L214

Currently this lib does not make an assumption that Primary Key Column will also be auto-incrementing (ie. will have Default value). As result auto-incrementing primary column needs to be listed in both `PrimaryKey` & `HasDefault` of the Table class

**Comment by xldenis** [comment]
That's fine except when the actual SQL is generated it will create something along the lines of 

```
INSERT INTO table ("id",....) VALUES (DEFAULT, ....)
```

When it should be generating

```
INSERT INTO table (...) VALUES (...)
```

Auto incrementing ids do _not_ have a default value. They are a third possible state for values. The `HaskW` representation is fine. However the `Write` representation needs to allow droppign that entire column from the sql when it's `nothing`.

**Comment by mageshb** [comment]
Probably I'm not getting the difference between having the DEFAULT in the insert and skipping that column altogether.
For Eg:

```
CREATE TABLE "User"
(
  uid serial NOT NULL,
  name text,
  age integer,
  CONSTRAINT uid_primary_key PRIMARY KEY (uid)
)
```

For the above table, following sql is going to produce the same result.

```
insert into "User" ("uid", "name", "age") VALUES (DEFAULT, 'foo', 30)
insert into "User" ("name", "age") VALUES ('foo', 30)
```

As far as generation of sql is concerned, to drop that column altogether, we need to make change in Opaleye library itself as this lib rely on Opaleye's query generation.

Regarding tri state, please refer to the following comment 
https://github.com/byteally/dbrecord-opaleye/issues/4#issuecomment-250448569

Can you please clarify on 

>  Write representation needs to allow droppign that entire column from the sql when it's nothing

**Comment by xldenis** [comment]
> Probably I'm not getting the difference between having the DEFAULT in the insert and skipping that column altogether.

Sorry, for some reason my table was generated incorrectly and the primary key did not set `default nextval('posts_id_seq'::regclass)`. 

> However the Write representation needs to allow dropping that entire column from the sql when it's nothing.

What I meant is that there needed to be a way to treat it as if there is no `id` column at all. Given that everything works now that the table is properly generated, that is no longer important.
